/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package gui;

import database.EmployeeDAO;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class ReportsForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportsForm.class.getName());

    /**
     * Creates new form ReportsForm
     */
    public ReportsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAllEmployees = new javax.swing.JButton();
        btnDepartmentReport = new javax.swing.JButton();
        btnSalaryReport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bar_chart_48px.png"))); // NOI18N
        jLabel1.setText("التقارير");

        btnAllEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/under_computer_30px.png"))); // NOI18N
        btnAllEmployees.setText("تقرير جميع الموظفين ");
        btnAllEmployees.addActionListener(this::btnAllEmployeesActionPerformed);

        btnDepartmentReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business Report_50px.png"))); // NOI18N
        btnDepartmentReport.setText("تقرير حسب القسم");
        btnDepartmentReport.addActionListener(this::btnDepartmentReportActionPerformed);

        btnSalaryReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profit Report_50px.png"))); // NOI18N
        btnSalaryReport.setText("تقرير الرواتب");
        btnSalaryReport.addActionListener(this::btnSalaryReportActionPerformed);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/renew_subscription_24px.png"))); // NOI18N
        btnBack.setText(" رجوع ");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "الرقم", "الاسم", "القسم", "الراتب"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAllEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalaryReport, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDepartmentReport, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                    .addComponent(btnSalaryReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDepartmentReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAllEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
Dashboard dashboard = new Dashboard();
dashboard.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAllEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllEmployeesActionPerformed
      loadEmployeesReport();  // TODO add your handling code here:
    }//GEN-LAST:event_btnAllEmployeesActionPerformed

    private void btnDepartmentReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentReportActionPerformed
     String department = javax.swing.JOptionPane.showInputDialog(
        this,
        "أدخل اسم القسم:"
);

if (department != null && !department.isEmpty()) {

    loadDepartmentReport(department);

}   // TODO add your handling code here:
    }//GEN-LAST:event_btnDepartmentReportActionPerformed

    private void btnSalaryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryReportActionPerformed
     String salaryText = javax.swing.JOptionPane.showInputDialog(
        this,
        "أدخل الحد الأدنى للراتب:"
);

if (salaryText != null && !salaryText.isEmpty()) {

    double salary = Double.parseDouble(salaryText);

    loadSalaryReport(salary);

}   // TODO add your handling code here:
    }//GEN-LAST:event_btnSalaryReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportsForm().setVisible(true));
    }
private void loadEmployeesReport() {

    try {

        EmployeeDAO dao = new EmployeeDAO();

        ResultSet rs = dao.getEmployees();

        DefaultTableModel model =
                (DefaultTableModel) tblReport.getModel();

        model.setRowCount(0);

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("username"),
                rs.getString("department"),
                rs.getDouble("salary")
            });

        }

    } catch (Exception e) {

        e.printStackTrace();

    }
}
private void loadDepartmentReport(String department) {

    try {

        EmployeeDAO dao = new EmployeeDAO();

        ResultSet rs = dao.getEmployeesByDepartment(department);

        DefaultTableModel model =
                (DefaultTableModel) tblReport.getModel();

        model.setRowCount(0);

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getInt("id"),
                rs.getString("username"),
                rs.getString("department"),
                rs.getDouble("salary")

            });

        }

    } catch (Exception e) {

        e.printStackTrace();

    }
    
}
private void loadSalaryReport(double salary) {

    try {

        EmployeeDAO dao = new EmployeeDAO();

        ResultSet rs = dao.getEmployeesBySalary(salary);

        DefaultTableModel model =
                (DefaultTableModel) tblReport.getModel();

        model.setRowCount(0);

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getInt("id"),
                rs.getString("username"),
                rs.getString("department"),
                rs.getDouble("salary")

            });

        }

    } catch (Exception e) {

        e.printStackTrace();

    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllEmployees;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDepartmentReport;
    private javax.swing.JButton btnSalaryReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables
}
